services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - node.name=es
      - discovery.type=single-node # single-node 로 만든다.
      - discovery.seed_hosts=es
      - ELASTIC_PASSWORD=ecubelabs
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - es-data:/usr/share/es/data
      - certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
    networks:
      - monstache-networks

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - monstache-networks

  mongodb:
    image: promise6424/mymongo:1.1.1
    container_name: mongodb
    # environment:
    #    - MONGO_INITDB_ROOT_USERNAME=root
    #    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db
      #- ./mongod.conf:/etc/mongod.conf.orig
    expose:
      - "27017"
    ports:
      - 27017:27017
    networks:
      - monstache-networks
    hostname: mongodb

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    container_name: mongo-express
    ports:
      - 27117:8081
    environment:
      - PORT=8081
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017/
    networks:
      - monstache-networks
    hostname: mongo-express

  monstache:
    restart: always
    image: rwynn/monstache:rel6
    container_name: monstache
    depends_on:
      - mongodb
      - es
    volumes:
      - ./monstache.config.toml:/monstache.config.toml
    command: -f ./monstache.config.toml &
    links:
      - es
    ports:
      - 8080:8080
    networks:
      - monstache-networks

volumes:
  certs:
    driver: local
  es-data:
    driver: local
  mongo-data:
    driver: local

networks:
  monstache-networks: