# Generated by Django 5.1 on 2024-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('close', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitpn', models.CharField(max_length=6)),
                ('banknm', models.CharField(max_length=20)),
                ('goodnm', models.CharField(max_length=50)),
                ('wayre', models.CharField(max_length=100)),
                ('materityinterest', models.TextField()),
                ('priority', models.TextField()),
                ('limit_rate', models.IntegerField()),
                ('retarget', models.TextField()),
                ('atmost', models.BigIntegerField()),
                ('interestnm', models.CharField(max_length=10)),
                ('typesave', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=30)),
                ('interestrate', models.IntegerField()),
                ('maxinterest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KoreaBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change', models.CharField(max_length=20)),
                ('one_month', models.CharField(max_length=20)),
                ('six_month', models.CharField(max_length=20)),
                ('one_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='P2p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change', models.CharField(max_length=20)),
                ('one_month', models.CharField(max_length=20)),
                ('six_month', models.CharField(max_length=20)),
                ('one_year', models.CharField(max_length=20)),
            ],
        ),
    ]
